// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSupabase } from '@/lib/supabase-mock';

import { getSupabaseConfig } from './config';

const cfg = getSupabaseConfig();

// Déterminer si on utilise le mock
const useMock = !cfg.url || cfg.url.includes('mock') || import.meta.env.VITE_USE_MOCK === 'true' || 
                import.meta.env.NODE_ENV === 'development';

console.log('🔧 Africa Suite Pulse - Configuration Supabase');
console.log('===============================================');
console.log('Mode:', useMock ? '🧪 MOCK (Tests)' : '🌐 PRODUCTION');
console.log('URL:', useMock ? 'mock://localhost:3000' : cfg.url);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = useMock ? mockSupabase : createClient<Database>(cfg.url, cfg.anon, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export pour compatibilité
export default supabase;

